stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "pipeline-testing"

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  services:
    - docker:dind
  script:
    - docker run --rm $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "Deploy to staging or production here"
  only:
    - master
