stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "pipeline-testing"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""  # Disable TLS verification for `docker:dind`

build:
  stage: build
  tags:
    - docker-build  # Runner tag for the build stage
  services:
    - docker:dind  # Use Docker-in-Docker
  script:
    - docker info  # Verify Docker is running and accessible
    - docker build -t $DOCKER_IMAGE .  # Build the Docker image

test:
  stage: test
  tags:
    - docker  # Runner tag for the test stage
  services:
    - docker:dind  # Use Docker-in-Docker
  script:
    - docker info  # Verify Docker is running and accessible
    - docker run --rm $DOCKER_IMAGE  # Run the container to execute tests

deploy:
  stage: deploy
  tags:
    - docker  # Runner tag for the deploy stage
  services:
    - docker:dind  # Use Docker-in-Docker
  script:
    - echo "Deploy our application here"
  only:
    - master  # Deploy only on the master branch
