stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "pipeline-testing"
  DOCKER_BUILDKIT: 1

build:
  stage: build
  services:
    - docker:dind:latest
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  script:
    - docker buildx create --use
    - docker buildx build --load -t $DOCKER_IMAGE .

test:
  stage: test
  services:
    - docker:dind:latest
  script:
    - docker run --rm $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "Deploy to staging or production here"
  only:
    - master
