stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "pipeline-testing"
  CONTAINER_NAME: "pipeline-testing"
  DJANGO_SETTINGS_MODULE: "resume_classification.settings"

# Build the Docker image with the application and tests
build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

# Run tests inside the Docker container
test:
  stage: test
  services:
    - docker:dind  # Docker-in-Docker to allow running Docker commands
  script:
    - docker run --name $CONTAINER_NAME --rm $DOCKER_IMAGE
  after_script:
    - docker logs $CONTAINER_NAME

# Deploy stage (not done right now)
deploy:
  stage: deploy
  script:
    - echo "Deploy to staging or production here"
  only:
    - master
